# Configuration de build pour Next.js sur Netlify
[build]
  command = "npm run build"
  publish = ".next"

# Variables d'environnement
[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"

# Plugin pour Next.js
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Sécurité HTTP headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"